### ISSUE TITLE
部署后访问超时？？

### ISSUE THREAD

**Issue by atticusWang** [samejack/web-k8s-exec#1]
``git clone``后执行``npm install``安装依赖，并用``node index.js``启动node进程，但是前端访问的时候报错，而且没看到项目监听host中的6443端口，报错如下:
```shell
Tue May 28 2019 18:48:50 GMT+0800 (CST) Server is listening on port 8443
Tue May 28 2019 18:49:02 GMT+0800 (CST) Connection accepted.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:6443
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
```

**Comment by samejack** [comment]
您的 K8S 有啟動嗎?

index.js 裡需要設定 k8s host, access token 與相關連線資訊
```
const token = "your access token";
const host = 'wss://192.168.0.1:6443';
const namespace = 'default';
const pod = 'kubebox-77c85fb6bb-vts74';
const container = 'kubebox';
const command = 'sh';
```

**Comment by atticusWang** [comment]
> 您的 K8S 有啟動嗎?
> 
> index.js 裡需要設定 k8s host, access token 與相關連線資訊
> 
> ```
> const token = "your access token";
> const host = 'wss://192.168.0.1:6443';
> const namespace = 'default';
> const pod = 'kubebox-77c85fb6bb-vts74';
> const container = 'kubebox';
> const command = 'sh';
> ```

是的，我已经在index.js中配置了相关参数，并且我本地通过``kubectl proxy``命令开启代理后是可以访问集群API服务的。

**Comment by samejack** [comment]
您可以先透過 curl 確認 6443 port 可以正常連線，另外如果 kubectl proxy 可以通，也可以把 host 改為 127.0.0.1 走 proxy 到集群中

**Comment by CodeDing** [comment]
我也遇到类似问题显示连接上了，但是终端报错且node退出，错误如下
Tue Jan 14 2020 14:20:08 GMT+0800 (CST) Server is listening on port 8080
Starting request ....
Tue Jan 14 2020 14:20:14 GMT+0800 (CST) ==== Connection accepted.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected server response: 403
    at ClientRequest.req.on (/home/michael1/web-k8s-exec/node_modules/ws/lib/websocket.js:595:7)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
