### ISSUE TITLE
websocket报错

### ISSUE THREAD

**Issue by CodeDing** [samejack/web-k8s-exec#2]
我也遇到类似问题显示连接上了，但是终端报错且node退出，错误如下
Tue Jan 14 2020 14:20:08 GMT+0800 (CST) Server is listening on port 8080
Starting request ....
Tue Jan 14 2020 14:20:14 GMT+0800 (CST) ==== Connection accepted.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected server response: 403
    at ClientRequest.req.on (/home/michael1/web-k8s-exec/node_modules/ws/lib/websocket.js:595:7)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)

_Originally posted by @CodeDing in https://github.com/samejack/web-k8s-exec/issues/1#issuecomment-574022221_

**Comment by samejack** [comment]
您的 token 是不是錯誤了？
```
Unexpected server response: 403
```
